# Example on continue-on-fail, where the workflow will continue running even
# some steps fail.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: continue-on-fail-
spec:
  entrypoint: workflow-ignore
  parallelism: 1
  templates:
  - name: workflow-ignore
    steps:
    - - name: A
        template: whalesay
    - - name: B
        template: whalesay
      - name: C
        template: intentional-fail
        continueOn:
          exitCode: 9
    - - name: D
        template: cowsay

  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]

  - name: intentional-fail
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo intentional failure; exit 9"]
  
  - name: cowsay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["bye bye  world"]
